#! /bin/bash

pkg_dir="pkg"
icon_dir="$PWD"/"$pkg_dir"/icons
theme_dir="$PWD"/"$pkg_dir"/themes
theme_src="$PWD"/theme-src

######################
### BUILD CURSOR THEME
######################

echo "Now building cursor theme
"

if [ ! -d "$icon_dir" ]; then
	mkdir -p "$icon_dir"/cursors
fi

cd cursor-src

#generate cursor files
for i in *.cursor
do
	filename=${i%.cursor}
	xcursorgen "$i" "$icon_dir"/cursors/"$filename"
done

cp cursor.theme "$icon_dir"

cd "$icon_dir"/cursors

#link remaining cursor icons
ln -s sb_v_double_arrow 00008160000006810000408080010102
ln -s sb_h_double_arrow 028006030e0e7ebffc7f7070c0600140
ln -s crossed_circle 03b6e0fcb3499374a867c041f52298f0
ln -s left_ptr_watch 08e8e1c95fe2fc01f976f1e063a24ccd
ln -s copy 1081e37283d90000800003c07f3ef6bf
ln -s sb_h_double_arrow 14fef782d02440884392942c11205230
ln -s sb_v_double_arrow 2870a09082c103050810ffdffffe0204
ln -s link 3085a0e285430894940527032f8b26df
ln -s left_ptr_watch 3ecb610c1bf2410f44200f48c40d3599
ln -s move 4498f0e0c1937ffe01fd06f973665830
ln -s help 5c6cd98b3f3ebcb1f9c7f1c204630408
ln -s copy 6407b0e94181790501fd1e167b474872
ln -s link 640fb0e74195791501fd1ed57b41487f
ln -s move 9081237383d90e509aa00f00170e968f
ln -s hand 9d800788f1b08800ae810202380a0822
ln -s left_ptr arrow
ln -s top_left_corner bd_double_arrow
ln -s top_right_corner bottom_left_corner
ln -s top_left_corner bottom_right_corner
ln -s sb_v_double_arrow bottom_side
ln -s sb_v_double_arrow bottom_tee
ln -s top_left_corner c7088f0f3e6c8088236ef8e1e3e70000
ln -s crosshair cross
ln -s crosshair cross_reverse
ln -s help d9ce0ab605698f320427677b458ad60b
ln -s crosshair diamond_cross
ln -s hand dnd-none
ln -s target dotbox
ln -s target dot_box_mask
ln -s sb_v_double_arrow double_arrow
ln -s right_ptr draft_large
ln -s right_ptr draft_small
ln -s target draped_box
ln -s hand e29285e634086352946a0e7090d73106
ln -s top_right_corner fcf1c3c7cd4491d801f1e1c78f100000
ln -s top_right_corner fd_double_arrow
ln -s hand fleur
ln -s hand grab
ln -s hand grabbing
ln -s hand hand1
ln -s hand hand2
ln -s sb_h_double_arrow h_double_arrow
ln -s target icon
ln -s sb_h_double_arrow left_side
ln -s sb_h_double_arrow left_tee
ln -s top_right_corner ll_angle
ln -s top_left_corner lr_angle
ln -s crossed_circle pirate
ln -s help question_arrow
ln -s sb_h_double_arrow right_side
ln -s sb_h_double_arrow right_tee
ln -s crosshair tcross
ln -s left_ptr top_left_arrow
ln -s sb_v_double_arrow top_side
ln -s sb_v_double_arrow top_tee
ln -s top_left_corner ul_angle
ln -s top_right_corner ur_angle
ln -s sb_v_double_arrow v_double_arrow
ln -s wait watch
ln -s crossed_circle X_cursor
ln -s ibeam xterm

cd ..

######################################
### BUILD GTK/CINNAMON/METACITY THEMES
######################################

echo "Now building gtk, cinnamon, and metacity themes
"

if [ ! -d "$theme_dir" ]; then
	mkdir -p "$theme_dir"/gtk-3.0
fi

cd "$theme_src"/gtk-3.0

#ensure gtk-contained is up to date
rm gtk-contained.css
./parse-sass.sh

#change compiled files here (currently uses all png images and css files in gtk-3.0)
files=$(find . -type  f \( -name "*.png" -or -name "*gtk-contained.css" \))

#build xml file for gtk.gresource
files=${files//.$'\n'/}
files=${files//'./'/'    <file>'}
files=${files//$'\n'/'</file>'$'\n'}
files="$files"'</file>'$'\n'

resource_path="/org/gnome/CinnXP"
xml_path="/tmp/gresources.xml"

header="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<gresources>
  <gresource prefix=\"$resource_path\">
"
footer="  </gresource>
</gresources>"

echo "$header$files$footer" > "$xml_path"

#build gtk3 resources file
glib-compile-resources --target="$theme_dir"/gtk-3.0/gtk.gresource /tmp/gresources.xml

echo '@import url("resource:///org/gnome/CinnXP/gtk-contained.css");' > "$theme_dir"/gtk-3.0/gtk.css

#~ rm "$xml_path"

#link everything else
ln -s "$theme_src"/{gtk-2.0,metacity-1,index.theme,cinnamon} "$theme_dir"
